{
 "title": "Panels",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "nodeexporter"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "CPULA 15"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time (node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}[20s])",
     "legendFormat": "nodeexporter"
    }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mode=\"idle\"}[10s]) * 100)"
    }
   ]
  }
 ]
}