FROM    centos:7
ARG     version=7.17.1
ENV     ES_HOME=/usr/share/elasticsearch ES_PATH_CONF=/usr/share/elasticsearch/config/

RUN     yum update -y && \
        yum install wget -y && \
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$version-linux-x86_64.tar.gz && \
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$version-linux-x86_64.tar.gz.sha512 && \
        sha512sum --check elasticsearch-$version-linux-x86_64.tar.gz.sha512 && \
        tar -xzf elasticsearch-$version-linux-x86_64.tar.gz && \
        rm elasticsearch-$version-linux-x86_64.tar.gz -f && \
        rm elasticsearch-$version-linux-x86_64.tar.gz.sha512 -f && \
        mv elasticsearch-$version $ES_HOME

COPY    elasticsearch.yml $ES_PATH_CONF/elasticsearch.yml

RUN     groupadd -g 1000 elasticsearch && \
        useradd elasticsearch -u 1000 -g 1000 && \
        chown -R elasticsearch:elasticsearch $ES_HOME && \
        mkdir /var/log/elasticsearch && \
        chmod 777 /var/log/elasticsearch && \
        chmod 777 /var/lib/

USER    elasticsearch

EXPOSE  9200 9300

CMD     ["/usr/share/elasticsearch/bin/elasticsearch"]


